name: Build Docker Image

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      image_uri: ${{ steps.tag_image.outputs.image_uri }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Login to Github Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Build Docker Image
        id: tag_image
        run: |
          docker build -t ghcr.io/sriniansiblegit/apache:latest .
          echo "::set-output name=image_uri::ghcr.io/sriniansiblegit/apache:latest"
